import { Spectral } from "next/font/google";
import "./globals.css";
import { Header } from "@/component/header";
import { Footer } from "@/component/footer";
const inter = Spectral({ subsets: ["latin"], weight: "400" });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
